### ISSUE TITLE
Channel not being subscribed

### ISSUE THREAD

**Issue by usmantariqdatainvent** [nerzh/Action-Cable-Swift#2] opened 2020-06-04 11:22 UTC
socket gets connected properly
channel welcome text comes
channel ping comes constantly
but addOnSubscribe closure never gets called

**Comment by nerzh** [comment] 2020-08-28 08:45
answer here
Duplicate of #3

**Comment by nerzh** [comment] 2020-08-28 10:03
answer here
Duplicate of #3

**Closed as completed by nerzh** 2020-08-28 10:03 UTC
